#!/usr/bin/env bash
set -euo pipefail

# AI Gateway Rollback Script
# Rolls back to the previous deployment color

# ============================================
# Configuration
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_ROOT/.." && pwd)"
DEPLOYMENTS_DIR="$PROJECT_ROOT/deployments"
LOG_FILE="$DEPLOYMENTS_DIR/deployments.log"
STATE_FILE="$DEPLOYMENTS_DIR/.deployment-state"
ACTIVE_UPSTREAM_FILE="$DEPLOYMENTS_DIR/.active-upstream"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ============================================
# Functions
# ============================================

log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "[$timestamp] [$level] $message" | tee -a "$LOG_FILE"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"
}

print_usage() {
    cat << EOF
Usage: $(basename "$0") [--scale-down-failed]

Rollback to the previous deployment color.

OPTIONS:
    --scale-down-failed    Scale down the failed deployment after rollback

ENVIRONMENT VARIABLES:
    FORCE_ROLLBACK         Skip confirmation prompt (true/false)

EXAMPLES:
    $(basename "$0")                    # Interactive rollback
    $(basename "$0") --scale-down-failed  # Rollback and scale down failed
    FORCE_ROLLBACK=true $(basename "$0")  # Non-interactive rollback

EOF
    exit 1
}

get_current_color() {
    if [[ -f "$ACTIVE_UPSTREAM_FILE" ]]; then
        cat "$ACTIVE_UPSTREAM_FILE"
    else
        echo "blue"
    fi
}

get_previous_color() {
    local current="$1"
    if [[ "$current" == "blue" ]]; then
        echo "green"
    else
        echo "blue"
    fi
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed or not in PATH"
        exit 1
    fi

    log_success "Prerequisites check passed"
}

confirm_rollback() {
    if [[ "${FORCE_ROLLBACK:-false}" == "true" ]]; then
        return 0
    fi

    echo ""
    log_warning "This will switch traffic back to the previous deployment."
    read -p "Are you sure you want to proceed? (yes/no): " confirmation

    if [[ "$confirmation" != "yes" ]]; then
        log_info "Rollback cancelled by user"
        exit 0
    fi
}

verify_previous_deployment() {
    local previous_color="$1"
    local port

    if [[ "$previous_color" == "blue" ]]; then
        port=8081
    else
        port=8082
    fi

    log_info "Verifying $previous_color deployment is healthy..."

    if curl -f -s "http://localhost:$port/health" > /dev/null 2>&1; then
        log_success "$previous_color deployment is healthy"
        return 0
    else
        log_error "$previous_color deployment is not healthy"
        log_error "Rollback cannot proceed safely"
        return 1
    fi
}

switch_traffic() {
    local target_color="$1"

    log_info "Switching traffic to $target_color..."

    # Call the switch-traffic script
    if bash "$SCRIPT_DIR/switch-traffic.sh" "$target_color"; then
        log_success "Traffic switched to $target_color"
        return 0
    else
        log_error "Failed to switch traffic to $target_color"
        return 1
    fi
}

scale_down_deployment() {
    local color="$1"

    log_info "Scaling down $color deployment..."

    cd "$DEPLOYMENTS_DIR/docker"

    if docker compose -f docker-compose.base.yml -f docker-compose.prod.yml \
        up -d --scale "ai-gateway-$color=0" 2>/dev/null; then
        log_success "Scaled down $color deployment"
        return 0
    else
        log_warning "Failed to scale down $color deployment"
        return 1
    fi
}

update_deployment_state() {
    local new_color="$1"
    local state_file="$DEPLOYMENTS_DIR/.deployment-state"

    if [[ -f "$state_file" ]]; then
        # Update existing state file
        local old_image_tag
        old_image_tag=$(grep "^IMAGE_TAG=" "$state_file" | cut -d'=' -f2)

        cat > "$state_file" << EOF
# Deployment State File
# Generated by rollback.sh

DEPLOYMENT_COLOR="$new_color"
IMAGE_TAG="$old_image_tag"
ROLLBACK_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
PREVIOUS_COLOR="$1"
EOF

        log_info "Updated deployment state: $new_color"
    fi
}

# ============================================
# Main Execution
# ============================================

main() {
    local scale_down_failed=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --scale-down-failed)
                scale_down_failed=true
                shift
                ;;
            -h|--help)
                print_usage
                ;;
            *)
                log_error "Unknown option: $1"
                print_usage
                ;;
        esac
    done

    log_info "========================================="
    log_info "AI Gateway Rollback"
    log_info "========================================="
    log_info "Started at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    # Check prerequisites
    check_prerequisites

    # Get current and previous colors
    local current_color
    local previous_color
    current_color=$(get_current_color)
    previous_color=$(get_previous_color "$current_color")

    log_info "Current deployment: $current_color"
    log_info "Previous deployment: $previous_color"

    # Confirm rollback
    confirm_rollback

    # Verify previous deployment is healthy
    if ! verify_previous_deployment "$previous_color"; then
        log_error "Cannot proceed with rollback"
        log_error "Previous deployment ($previous_color) is not healthy"
        log_info "You may need to investigate the issue manually"
        exit 1
    fi

    # Switch traffic to previous deployment
    if ! switch_traffic "$previous_color"; then
        log_error "Rollback failed at traffic switch stage"
        exit 1
    fi

    # Scale down failed deployment if requested
    if [[ "$scale_down_failed" == "true" ]]; then
        scale_down_deployment "$current_color"
    fi

    # Update deployment state
    update_deployment_state "$previous_color"

    log_success "========================================="
    log_success "Rollback completed successfully!"
    log_success "Active deployment: $previous_color"
    log_success "Rolled back from: $current_color"
    log_success "Completed at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    log_success "========================================="

    # Provide next steps
    if [[ "$scale_down_failed" != "true" ]]; then
        echo ""
        log_info "To scale down the failed deployment:"
        log_info "  docker compose -f deployments/docker/docker-compose.base.yml \\"
        log_info "    -f deployments/docker/docker-compose.prod.yml \\"
        log_info "    up -d --scale ai-gateway-$current_color=0"
    fi

    exit 0
}

# Run main function
main "$@"
