#!/usr/bin/env bash
set -euo pipefail

# AI Gateway Traffic Switch Script
# Switches traffic between blue and green deployments by updating nginx configuration

# ============================================
# Configuration
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEPLOYMENTS_DIR="$PROJECT_ROOT/deployments"
LOG_FILE="$DEPLOYMENTS_DIR/deployments.log"
NGINX_CONF_DIR="$PROJECT_ROOT/nginx"
ACTIVE_UPSTREAM_FILE="$DEPLOYMENTS_DIR/.active-upstream"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ============================================
# Functions
# ============================================

log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "[$timestamp] [$level] $message" | tee -a "$LOG_FILE"
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*" | tee -a "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*" | tee -a "$LOG_FILE"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"
}

print_usage() {
    cat << EOF
Usage: $(basename "$0") <target_color>

Switch traffic to the specified deployment color.

ARGUMENTS:
    target_color   Target deployment color (blue|green)

EXAMPLES:
    $(basename "$0") blue
    $(basename "$0") green

EOF
    exit 1
}

validate_arguments() {
    if [[ "$#" -ne 1 ]]; then
        log_error "Invalid arguments"
        print_usage
    fi

    TARGET_COLOR="$1"

    if [[ ! "$TARGET_COLOR" =~ ^(blue|green)$ ]]; then
        log_error "Invalid color: $TARGET_COLOR"
        log_info "Valid colors: blue, green"
        exit 1
    fi

    log_info "Traffic switch configuration:"
    log_info "  Target color: $TARGET_COLOR"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed or not in PATH"
        exit 1
    fi

    # Check if nginx container is running
    if ! docker ps --format '{{.Names}}' | grep -q 'ai-gateway-nginx'; then
        log_warning "nginx container is not running"
        log_info "Starting nginx..."
        cd "$DEPLOYMENTS_DIR/docker"
        docker compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d nginx || {
            log_error "Failed to start nginx"
            exit 1
        }
        sleep 5
    fi

    log_success "Prerequisites check passed"
}

get_current_upstream() {
    if [[ -f "$ACTIVE_UPSTREAM_FILE" ]]; then
        cat "$ACTIVE_UPSTREAM_FILE"
    else
        echo "blue"
    fi
}

switch_nginx_upstream() {
    local target_color="$1"

    log_info "Switching nginx upstream to $target_color..."

    # Update the active upstream file
    echo "$target_color" > "$ACTIVE_UPSTREAM_FILE"

    # Update nginx configuration
    local upstream_conf="$NGINX_CONF_DIR/conf.d/upstream.conf"

    cat > "$upstream_conf" << EOF
# Active upstream configuration
# Generated by switch-traffic.sh

upstream ai_gateway_active {
    least_conn;
    server ai-gateway-$target_color:8080 max_fails=3 fail_timeout=30s;
    keepalive 32;
}
EOF

    log_info "Updated upstream configuration"

    # Reload nginx
    log_info "Reloading nginx configuration..."

    if docker exec ai-gateway-nginx nginx -t > /dev/null 2>&1; then
        docker exec ai-gateway-nginx nginx -s reload
        log_success "nginx reloaded successfully"
        return 0
    else
        log_error "nginx configuration test failed"
        log_error "Rolling back configuration change..."
        rollback_nginx_upstream "$(get_current_upstream)"
        return 1
    fi
}

verify_traffic_switch() {
    local target_color="$1"
    local expected_port
    local health_url="http://localhost/health"

    if [[ "$target_color" == "blue" ]]; then
        expected_port=8081
    else
        expected_port=8082
    fi

    log_info "Verifying traffic switch to $target_color..."

    # Wait a moment for nginx to reload
    sleep 2

    # Check health endpoint
    local attempts=0
    local max_attempts=10

    while [[ $attempts -lt $max_attempts ]]; do
        if curl -f -s "$health_url" > /dev/null 2>&1; then
            log_success "Traffic switch verified - health endpoint responding"
            return 0
        fi

        ((attempts++))
        echo -ne "\rVerifying... ($attempts/$max_attempts) "
        sleep 1
    done

    echo ""
    log_error "Traffic switch verification failed - health endpoint not responding"
    return 1
}

rollback_nginx_upstream() {
    local previous_color="$1"

    log_warning "Rolling back to $previous_color upstream..."

    # Restore previous configuration
    local upstream_conf="$NGINX_CONF_DIR/conf.d/upstream.conf"

    cat > "$upstream_conf" << EOF
# Active upstream configuration
# Generated by switch-traffic.sh (rollback)

upstream ai_gateway_active {
    least_conn;
    server ai-gateway-$previous_color:8080 max_fails=3 fail_timeout=30s;
    keepalive 32;
}
EOF

    # Reload nginx
    if docker exec ai-gateway-nginx nginx -t > /dev/null 2>&1; then
        docker exec ai-gateway-nginx nginx -s reload
        log_success "Rollback completed"
    else
        log_error "Rollback failed - manual intervention required"
    fi
}

# ============================================
# Main Execution
# ============================================

main() {
    log_info "========================================="
    log_info "AI Gateway Traffic Switch"
    log_info "========================================="
    log_info "Started at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

    # Validate arguments
    validate_arguments "$@"

    # Check prerequisites
    check_prerequisites

    # Get current upstream
    local current_upstream
    current_upstream=$(get_current_upstream)
    log_info "Current upstream: $current_upstream"

    # Switch nginx upstream
    if ! switch_nginx_upstream "$TARGET_COLOR"; then
        log_error "Traffic switch failed"
        exit 1
    fi

    # Verify traffic switch
    if ! verify_traffic_switch "$TARGET_COLOR"; then
        log_error "Traffic switch verification failed"
        log_warning "Rolling back to previous configuration..."
        rollback_nginx_upstream "$current_upstream"
        exit 1
    fi

    log_success "========================================="
    log_success "Traffic switch completed successfully!"
    log_success "Active upstream: $TARGET_COLOR"
    log_success "Completed at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    log_success "========================================="

    exit 0
}

# Run main function
main "$@"
